name: example-action
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "I am an action"
          echo "Look at me running!"
